font_family      family="FiraCode Nerd Font Mono" style=Regular
bold_font        family="FiraCode Nerd Font Mono" style=Bold
italic_font      family="FiraCode Nerd Font Mono" style=Regular
bold_italic_font family="FiraCode Nerd Font Mono" style=Bold

disable_ligatures never

font_size 18


# BEGIN_KITTY_THEME
# Cherry Midnight
include current-theme.conf
# END_KITTY_THEME

# Padding
window_padding_width 18
